import { Product, Category, Promo, User } from "./schema";

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Menu Kukusan",
    slug: "menu-kukusan",
    description: "Kukusan hangat alami tanpa minyak",
    icon: "Flame",
    displayOrder: 1,
    isActive: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Pisang Kukus Alami",
    slug: "pisang-kukus-alami",
    description: "Pisang manis pulen dikukus hangat dengan kulit alami, cocok untuk sarapan & ganjal lapar.",
    price: 2000,
    originalPrice: 2500,
    categoryId: "cat-1",
    imageUrl: "/menu/pisang.jpg",
    badge: "2K / Pcs",
    isActive: true,
    isFeatured: true,
    displayOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-2",
    name: "Ubi Oren Kukus",
    slug: "ubi-oren-kukus",
    description: "Ubi oren manis lembut kaya nutrisi & serat alami, dikukus fresh setiap pagi.",
    price: 2000,
    originalPrice: 2500,
    categoryId: "cat-1",
    imageUrl: "/menu/ubi-oren.jpg",
    badge: "2K / Pcs",
    isActive: true,
    isFeatured: true,
    displayOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-3",
    name: "Ubi Ungu Kukus",
    slug: "ubi-ungu-kukus",
    description: "Ubi ungu pulen tinggi antioksidan alami, rasa manis pas tanpa pemanis tambahan.",
    price: 2000,
    originalPrice: 2500,
    categoryId: "cat-1",
    imageUrl: "/menu/ubi-ungu.jpg",
    badge: "2K / Pcs",
    isActive: true,
    isFeatured: true,
    displayOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-4",
    name: "Singkong Kukus",
    slug: "singkong-kukus",
    description: "Singkong empuk merekah dikukus matang sempurna, gurih manis alami khas Nusantara.",
    price: 2000,
    originalPrice: 2500,
    categoryId: "cat-1",
    imageUrl: "/menu/singkong.jpg",
    badge: "2K / Pcs",
    isActive: true,
    isFeatured: true,
    displayOrder: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-5",
    name: "Talas Kukus",
    slug: "talas-kukus",
    description: "Talas pilihan yang pulen dan legit, dikukus bersih murni tanpa bahan pengawet.",
    price: 2000,
    originalPrice: 2500,
    categoryId: "cat-1",
    imageUrl: "/menu/talas.jpg",
    badge: "2K / Pcs",
    isActive: true,
    isFeatured: true,
    displayOrder: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-6",
    name: "Kentang Kukus",
    slug: "kentang-kukus",
    description: "Kentang segar pilihan dikukus empuk pulen alami, lembut bergizi dan mengenyangkan.",
    price: 2000,
    originalPrice: 2500,
    categoryId: "cat-1",
    imageUrl: "/menu/kentang.jpg",
    badge: "2K / Pcs",
    isActive: true,
    isFeatured: true,
    displayOrder: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-7",
    name: "Jagung Manis Kukus",
    slug: "jagung-manis-kukus",
    description: "Jagung manis segar berkualitas, bulir juicy renyah dan harum saat disantap hangat.",
    price: 2000,
    originalPrice: 2500,
    categoryId: "cat-1",
    imageUrl: "/menu/jagung.jpg",
    badge: "2K / Pcs",
    isActive: true,
    isFeatured: true,
    displayOrder: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod-8",
    name: "Paket Hemat 5K Dapet 3 Pcs",
    slug: "paket-hemat-5k-dapet-3",
    description: "Bebas campur 3 biji varian kukusan apa saja (Pisang, Ubi Oren, Ubi Ungu, Kentang, Singkong, Talas, Jagung) cuma Rp 5.000!",
    price: 5000,
    originalPrice: 6000,
    categoryId: "cat-1",
    imageUrl: "/menu/paket-3pcs.jpg",
    badge: "Hemat 5K!",
    isActive: true,
    isFeatured: true,
    displayOrder: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const INITIAL_SITE_CONTENT = {
  hero: {
    title: "Kukusan Hangat Alami, Rasa Nikmat Setiap Hari",
    subtitle: "Jajanan kukus murni tanpa minyak: Pisang, Ubi Oren, Ubi Ungu, Kentang, Singkong, Talas, & Jagung. Buka Jam 06.00 - Habis. Serba Rp 2.000/pcs & Promo 5K Dapet 3 Pcs! Siap antar daerah Kampus UMP 1.",
    badgeText: "🛵 Siap Antar Daerah Kampus UMP 1 | Buka Jam 06.00 - Habis",
    ctaPrimaryText: "Pesan via WhatsApp (08818584749)",
    ctaSecondaryText: "Lihat Menu Kukusan",
    heroImageUrl: "/banners/header-banner.jpg",
  },
  identity: {
    brandName: "Kukusan Gen Z",
    tagline: "Kukusan Sehat, Rasa Hebat",
    logoText: "Kukusan Gen Z",
    whatsappNumber: "628818584749",
    instagramUrl: "https://www.instagram.com/kukusangenz._?stkn=N2JhYW85bml3czJu",
    tiktokUrl: "https://www.tiktok.com/@kukusangenz_?_r=1&_t=ZS-9A8P0eyM0If",
  },
  about: {
    title: "Tentang Kukusan Gen Z",
    subtitle: "Lapak Nyata di Ketapang Kost 2 Dukuhwaluh",
    description: "Kukusan Gen Z adalah usaha kuliner kukusan murni yang hadir langsung di depan gerbang Ketapang Kost 2, Dukuhwaluh, Kembaran, Banyumas. Kami menyajikan aneka kukusan sehat serba Rp 2.000 (Pisang, Ubi Oren, Ubi Ungu, Kentang, Singkong, Talas, Jagung) yang dikukus hangat setiap hari mulai jam 6 pagi. Menerima pesanan porsi besar & kecil serta siap antar ke area Kampus UMP 1 dan kos-kosan sekitarnya!",
    bulletPoints: [
      "Lapak Stand Nyata di Depan Ketapang Kost 2 Dukuhwaluh",
      "Buka Setiap Pagi Mulai Jam 06.00 WIB - Sampai Habis",
      "Aneka Kukusan Sehat Serba 2.000 & Paket Hemat 5K Dapet 3 Pcs",
      "Menerima Pesanan Porsi Besar & Kecil (Siap Antar Kampus UMP 1)",
    ],
    imageUrl: "/banners/about-banner.jpg",
  },
  advantages: [
    {
      id: "adv-1",
      icon: "Clock",
      title: "Buka Jam 06.00 - Sampai Habis",
      description: "Dikukus hangat tiap pagi jam 6 di lapak Ketapang Kost 2, pas untuk sarapan sebelum kuliah.",
    },
    {
      id: "adv-2",
      icon: "Truck",
      title: "Siap Antar Area UMP 1",
      description: "Tinggal chat via WA 08818584749, kami antar langsung ke gerbang kampus / kos sekitar.",
    },
    {
      id: "adv-3",
      icon: "Flame",
      title: "100% Bebas Minyak",
      description: "Murni aneka kukusan sehat alami tanpa gorengan, aman di lambung dan sehat.",
    },
    {
      id: "adv-4",
      icon: "HeartHandshake",
      title: "Serba 2K & 5K Dapet 3",
      description: "Harga satuan Rp 2.000 & paket 3 biji cuma Rp 5.000. Super ramah di kantong mahasiswa.",
    },
  ],
  promos: [],
  testimonials: [
    {
      id: "testi-1",
      name: "Rian Pratama",
      role: "Mahasiswa Farmasi UMP",
      avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80",
      quote: "Langganan tiap pagi sebelum praktikum. Pisang sama ubi rebusnya masih anget banget, 5 ribu dapet 3 udah kenyang buat ganjal perut sebelum masuk kelas.",
      rating: 5,
    },
    {
      id: "testi-2",
      name: "Nabila Putri",
      role: "Anak Kost Dukuhwaluh",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
      quote: "Cemilan sehat yang beneran tanpa minyak. Singkong sama kentangnya empuk pulen. Murah meriah cuma 2 ribuan, cocok buat ngemil pas nugas malam di kost.",
      rating: 5,
    },
    {
      id: "testi-3",
      name: "Pak Hendro",
      role: "Warga Sekitar Ketapang",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      quote: "Sering mampir beli talas sama jagung manis kukusnya buat sarapan di rumah. Rasanya manis alami tanpa pemanis buatan, penjualnya juga ramah dan tempatnya bersih.",
      rating: 5,
    },
  ],
  location: {
    address: "Ketapang Kost 2, Dusun III, Dukuhwaluh, Kec. Kembaran, Kabupaten Banyumas, Jawa Tengah (Buka Pagi 06.00 - Habis | Siap Antar UMP 1)",
    weekdayLocation: "H7QG+945, Dusun III, Dukuhwaluh, Kec. Kembaran, Kabupaten Banyumas, Jawa Tengah (di depan Lare Cost_Food Corner)",
    weekendLocation: "H7QF+33X, Dusun III, Dukuhwaluh, Kec. Kembaran, Kabupaten Banyumas, Jawa Tengah 53182",
    openingHours: "06.00 WIB - Sampai Habis",
    phone: "08818584749",
    mapsEmbedUrl: "https://maps.google.com/maps?q=H7QG%2B945%2C+Dusun+III%2C+Dukuhwaluh%2C+Kec.+Kembaran%2C+Kabupaten+Banyumas%2C+Jawa+Tengah&t=&z=15&ie=UTF8&iwloc=&output=embed",
  },
};

export const DEFAULT_ADMIN: User = {
  id: "admin-1",
  name: "Admin Kukusan Gen Z",
  email: process.env.ADMIN_EMAIL || "admin@kukusangenz.com",
  password: process.env.ADMIN_PASSWORD || "admin123",
  role: "admin",
  createdAt: new Date(),
};
